INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (1, '学生模块', '删除学生', 16, null, '2026-02-13 11:31:23', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 20);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (2, '学生模块', '删除学生', 16, null, '2026-02-13 11:31:49', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 7);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (3, '学生模块', '删除学生', 16, null, '2026-02-13 12:17:35', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 23);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (4, '学生模块', '删除学生', 16, null, '2026-02-13 12:17:39', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 7);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (5, '学生模块', '删除学生', 16, null, '2026-02-13 12:19:12', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 16);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (6, '学生模块', '删除学生', 16, null, '2026-02-13 12:19:17', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 15);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (7, '学生模块', '删除学生', 16, null, '2026-02-13 12:19:45', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 28);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (8, '学生模块', '删除学生', 16, null, '2026-02-13 12:20:14', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, null, 16);
INSERT INTO school_db.sys_operation_log (id, module, type, operator_id, operator_name, operation_time, method_name, params, result, error_msg, cost_time) VALUES (9, '学生模块', '删除学生', 16, null, '2026-02-13 17:51:06', 'com.liu.studentmanagement.service.studentService.StudentServiceImpl.deleteStudent', null, null, 'Unable to connect to Redis', 25);
